"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, ClipboardCheck, Clock3, FileAudio, RefreshCw, ShieldCheck } from "lucide-react";
import { ApiError, getModerationQueue, type Contribution } from "../../lib/api-client";
import { BottomNav } from "../../components/BottomNav";
import { Badge, Button, CardSkeleton, FeedbackState, PageHeader, SearchBar } from "../../components/ui";
export default function ModerationQueuePage() {
  const [queue, setQueue] = useState<Contribution[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"all" | "sensitive">("all"); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true);
  function load() { setLoading(true); setError(undefined); getModerationQueue().then(setQueue).catch((err) => setError(err instanceof ApiError ? err.message : "Không tải được hàng đợi.")).finally(() => setLoading(false)); }
  useEffect(load, []);
  const items = useMemo(() => queue.filter((item) => (filter === "all" || item.sensitive) && `${item.proposedKhmerText ?? ""} ${item.proposedMeaningVi ?? ""} ${item.attributionName ?? ""}`.toLowerCase().includes(query.toLowerCase())), [queue, query, filter]);
  const sensitiveCount = queue.filter((item) => item.sensitive).length;
  return <main className="app-page moderation-page" style={{ paddingBottom: 88 }}><PageHeader eyebrow="Không gian reviewer" title="Hàng đợi kiểm duyệt" subtitle="Nghe, kiểm tra quyền sử dụng và đưa ra quyết định có lý do cho từng đóng góp." actions={<Button variant="secondary" onClick={load} disabled={loading}><RefreshCw className={loading ? "ps-spin" : ""} size={16} /> Làm mới</Button>} /><section className="moderation-layout"><div className="moderation-stats"><article><ClipboardCheck size={20} /><div><strong>{queue.length}</strong><span>Đang chờ xem xét</span></div></article><article><AlertTriangle size={20} /><div><strong>{sensitiveCount}</strong><span>Nội dung nhạy cảm</span></div></article><article><ShieldCheck size={20} /><div><strong>3 bước</strong><span>Nghe · quyền · quyết định</span></div></article></div><div className="moderation-toolbar"><SearchBar value={query} onChange={(event) => setQuery(event.target.value)} onClear={() => setQuery("")} label="Tìm trong hàng đợi" placeholder="Tìm nội dung hoặc người đóng góp" /><div><Button variant={filter === "all" ? "primary" : "secondary"} onClick={() => setFilter("all")}>Tất cả</Button><Button variant={filter === "sensitive" ? "primary" : "secondary"} onClick={() => setFilter("sensitive")}><AlertTriangle size={15} /> Nhạy cảm</Button></div></div>{loading && <div className="moderation-grid">{Array.from({ length: 6 }, (_, index) => <CardSkeleton key={index} lines={3} />)}</div>}{error && <FeedbackState kind={error.toLowerCase().includes("quyền") ? "permission" : "error"} title="Không mở được hàng đợi" description={error} action={<Button onClick={load}>Thử lại</Button>} />}{!loading && !error && !items.length && <div className="moderation-empty"><ClipboardCheck size={30} /><h2>{query || filter !== "all" ? "Không có kết quả phù hợp" : "Hàng đợi đã được xử lý hết"}</h2><p>{query || filter !== "all" ? "Hãy đổi từ khóa hoặc bỏ bộ lọc." : "Hiện không có đóng góp nào đang chờ duyệt."}</p>{(query || filter !== "all") && <Button variant="secondary" onClick={() => { setQuery(""); setFilter("all"); }}>Xóa bộ lọc</Button>}</div>}{!loading && !error && <div className="moderation-grid">{items.map((item) => <Link key={item.id} href={`/moderation/${item.id}`} className="moderation-card"><div className="moderation-card__top"><span><FileAudio size={19} /></span>{item.sensitive && <Badge variant="warning" icon={<AlertTriangle size={12} />}>Nhạy cảm</Badge>}</div><h2 lang={item.proposedKhmerText ? "km" : undefined}>{item.proposedKhmerText ?? "Bản ghi cho từ đã có"}</h2><p>{item.proposedMeaningVi ?? "Cần nghe bản ghi và đối chiếu từ vựng liên quan."}</p><div className="moderation-card__meta"><span><Clock3 size={13} /> {new Date(item.createdAt).toLocaleString("vi-VN", { dateStyle: "short", timeStyle: "short" })}</span><span>{item.attributionName ?? "Ẩn danh"}</span></div><strong className="moderation-card__action">Mở hồ sơ kiểm duyệt <ArrowRight size={15} /></strong></Link>)}</div>}</section><BottomNav /></main>;
}
