"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Building2, CheckCircle2, Loader2, School, ShieldCheck, UsersRound } from "lucide-react";
import { ApiError, createOrganization } from "../../../lib/api-client";
import { Button, Card, FeedbackState, PageHeader } from "../../../components/ui";
const TYPES = [{ value: "PAGODA", label: "Chùa" }, { value: "SCHOOL", label: "Trường học" }, { value: "CLUB", label: "Câu lạc bộ" }, { value: "MUSEUM", label: "Bảo tàng" }, { value: "AGENCY", label: "Cơ quan" }, { value: "PROJECT_TEAM", label: "Đội dự án" }];
export default function NewOrganizationPage() {
 const router = useRouter(); const [name, setName] = useState(""); const [type, setType] = useState("PAGODA"); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
 async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(undefined); try { const org = await createOrganization({ name: name.trim(), orgType: type }); router.push(`/organizations/${org.id}`); } catch (err) { setError(err instanceof ApiError ? err.message : "Không gửi được yêu cầu."); } finally { setBusy(false); } }
 return <main className="app-page org-register"><PageHeader backHref="/" eyebrow="Organization Self-service" title="Đăng ký tổ chức" subtitle="Dành cho đơn vị muốn tổ chức phòng thi, quản lý thành viên và theo dõi hoạt động trên PhumSpace." /><section className="org-register__layout"><Card className="org-register__form"><div className="org-register__icon"><Building2 size={25} /></div><h2>Thông tin cơ bản</h2><p>Hãy dùng tên chính thức để quản trị viên dễ xác minh.</p><form onSubmit={submit}><label className="ps-field"><span className="ps-field-label">Tên tổ chức</span><input className="ps-input" required minLength={2} maxLength={200} value={name} onChange={(event) => setName(event.target.value)} placeholder="Ví dụ: Trường PTDTNT Trà Vinh" /></label><label className="ps-field"><span className="ps-field-label">Loại hình</span><select className="ps-select" value={type} onChange={(event) => setType(event.target.value)}>{TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{error && <FeedbackState title="Chưa gửi được yêu cầu" description={error} />}<Button type="submit" disabled={busy}>{busy ? <Loader2 className="ps-spin" size={17} /> : <Building2 size={17} />} {busy ? "Đang gửi…" : "Gửi yêu cầu xác minh"}</Button></form></Card><aside className="org-register__steps"><h2>Điều gì xảy ra tiếp theo?</h2><ol><li><span><CheckCircle2 size={18} /></span><div><strong>Gửi yêu cầu</strong><p>Tổ chức được tạo ở trạng thái chờ duyệt.</p></div></li><li><span><ShieldCheck size={18} /></span><div><strong>Quản trị viên xác minh</strong><p>Kiểm tra tên, loại hình và tính phù hợp của đơn vị.</p></div></li><li><span><UsersRound size={18} /></span><div><strong>Bắt đầu quản lý</strong><p>Sau khi kích hoạt, manager có thể thêm thành viên và xem báo cáo.</p></div></li></ol><div className="org-register__note"><School size={18} /><p>PhumSpace không tự cấp trạng thái xác minh chỉ dựa trên việc đăng ký.</p></div></aside></section></main>;
}
