"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, Crown, LogOut, Medal, Trophy, X } from "lucide-react";
import { ApiError, getCompetitionQuestions, getLeaderboard, joinCompetition, submitCompetitionAnswer, type Competition, type LeaderboardEntry, type QuizQuestion, type QuizSubmissionResult } from "../../../../lib/api-client";
import { Button, Card, CardSkeleton, FeedbackState, PageHeader } from "../../../../components/ui";
const POLL_MS = 3000;
export function RoomQuizView({ roomCode }: { roomCode: string }) {
  const [competition, setCompetition] = useState<Competition | null>(null); const [questions, setQuestions] = useState<QuizQuestion[]>([]); const [index, setIndex] = useState(0); const [result, setResult] = useState<QuizSubmissionResult | null>(null); const [leaders, setLeaders] = useState<LeaderboardEntry[]>([]); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { joinCompetition(roomCode).then(async (joined) => { setCompetition(joined); setQuestions(await getCompetitionQuestions(joined.id)); }).catch((err) => setError(err instanceof ApiError ? err.message : "Không thể vào phòng thi.")).finally(() => setLoading(false)); }, [roomCode]);
  useEffect(() => { if (!competition) return; const refresh = () => getLeaderboard(competition.id).then(setLeaders).catch(() => undefined); refresh(); const timer = setInterval(refresh, POLL_MS); return () => clearInterval(timer); }, [competition]);
  const current = questions[index]; const finished = questions.length > 0 && index >= questions.length;
  async function answer(choiceId: string) { if (!current || !competition || submitting || result) return; setSubmitting(true); try { setResult(await submitCompetitionAnswer(competition.id, current.id, choiceId, current.version, crypto.randomUUID())); } catch (err) { setError(err instanceof ApiError ? err.message : "Không gửi được câu trả lời."); } finally { setSubmitting(false); } }
  if (loading) return <main className="quiz-play"><PageHeader backHref="/quiz" title={`Đang vào phòng ${roomCode}`} /><div className="room-layout"><CardSkeleton lines={5} /></div></main>;
  if (!competition) return <main className="quiz-play"><PageHeader backHref="/quiz" title="Không thể vào phòng thi" /><div className="quiz-shell"><FeedbackState title="Mã phòng chưa hợp lệ" description={error ?? "Phòng không tồn tại hoặc đã đóng."} action={<Link href="/quiz" className="ps-btn ps-btn--secondary">Nhập mã khác</Link>} /></div></main>;
  return <main className="quiz-play"><PageHeader backHref="/quiz" eyebrow={`PHÒNG ${roomCode}`} title={competition.title} actions={<Link href="/quiz" className="ps-btn ps-btn--ghost"><LogOut size={16} /> Rời phòng</Link>} /><section className="room-layout"><div>{!finished && current ? <><div className="quiz-progress"><span style={{ width: `${((index + 1) / questions.length) * 100}%` }} /></div><Card className="quiz-question"><small>CÂU {index + 1} / {questions.length}</small><h1>{current.questionText}</h1><div className="quiz-choices">{current.choices.map((choice, order) => <button key={choice.id} disabled={!!result || submitting} onClick={() => answer(choice.id)} className={`quiz-choice ${choiceStateClass(result, choice.id)}`}><span>{String.fromCharCode(65 + order)}</span><strong>{choice.text}</strong>{result?.correctChoiceId === choice.id && <Check size={18} />}{result?.selectedChoiceId === choice.id && !result.isCorrect && <X size={18} />}</button>)}</div></Card>{result && <Card className={`quiz-feedback quiz-feedback--${result.isCorrect ? "correct" : "wrong"}`}><span>{result.isCorrect ? <CheckCircle2 /> : <X />}</span><div><h2>{result.isCorrect ? "Chính xác!" : "Chưa đúng"}</h2>{result.explanation && <p>{result.explanation}</p>}</div><Button onClick={() => { setResult(null); setIndex((old) => old + 1); }}>{index + 1 < questions.length ? "Câu tiếp theo" : "Hoàn thành"} <ArrowRight size={16} /></Button></Card>}</> : <Card className="room-finished"><Trophy size={32} /><h2>{questions.length ? "Bạn đã hoàn thành!" : "Phòng chưa có câu hỏi"}</h2><p>{questions.length ? "Bảng xếp hạng sẽ tự cập nhật sau mỗi 3 giây." : "Hãy chờ người tổ chức bổ sung nội dung."}</p></Card>}{error && <FeedbackState title="Có sự cố trong phòng" description={error} />}</div><aside className="leaderboard"><div><Trophy size={20} /><h2>Bảng xếp hạng</h2><span>Tự cập nhật</span></div>{leaders.length ? <ol>{leaders.map((entry, order) => <li key={entry.userId}><span>{order === 0 ? <Crown size={18} /> : order < 3 ? <Medal size={18} /> : order + 1}</span><strong>{entry.displayName}</strong><small>{entry.correctCount}/{entry.answeredCount} đúng</small></li>)}</ol> : <p>Chưa có người chơi nộp đáp án.</p>}</aside></section></main>;
}
function choiceStateClass(result: QuizSubmissionResult | null, choiceId: string) { if (!result) return ""; if (result.correctChoiceId === choiceId) return "quiz-choice--correct"; if (result.selectedChoiceId === choiceId) return "quiz-choice--wrong"; return "quiz-choice--muted"; }
