"use client";
import "./drafts.css";
import { useEffect,useState } from "react";
import Link from "next/link";
import { FilePenLine,Loader2,Trash2 } from "lucide-react";
import { deleteContributionDraft,listContributionDrafts,saveContributionDraft,type ContributionDraft } from "../../../lib/api-client";
import { Button,Card,FeedbackState,PageHeader } from "../../../components/ui";
const TYPES=["ENTITY","CORRECTION","AUDIO","IMAGE","VIDEO","STORY","TERM","PLACE","SOURCE"];
export default function DraftsPage(){const [drafts,setDrafts]=useState<ContributionDraft[]>([]),[active,setActive]=useState<ContributionDraft>();const [type,setType]=useState("STORY"),[title,setTitle]=useState(""),[context,setContext]=useState(""),[saving,setSaving]=useState(false),[savedAt,setSavedAt]=useState<string>(),[error,setError]=useState<string>();
  function load(){listContributionDrafts().then(setDrafts).catch(()=>setError("Không tải được bản nháp."));} useEffect(load,[]);
  useEffect(()=>{if(!title&&!context)return;const timer=setTimeout(async()=>{setSaving(true);try{const value=await saveContributionDraft({id:active?.id,contributionType:type,payload:{title,context}});setActive(value);setSavedAt(new Date(value.updated_at).toLocaleTimeString("vi-VN"));load();}catch{setError("Autosave chưa thành công.");}finally{setSaving(false);}},800);return()=>clearTimeout(timer);},[title,context,type,active?.id]);
  function open(item:ContributionDraft){setActive(item);setType(item.contribution_type);setTitle(String(item.payload.title??""));setContext(String(item.payload.context??""));}
  async function remove(item:ContributionDraft){await deleteContributionDraft(item.id);if(active?.id===item.id){setActive(undefined);setTitle("");setContext("");}load();}
  return <main className="app-page"><PageHeader backHref="/contribute" eyebrow="Đóng góp cộng đồng" title="Bản nháp của tôi" subtitle="Tự động lưu vào tài khoản để bạn có thể tiếp tục trên thiết bị khác."/><section className="draft-workspace"><aside><Button onClick={()=>{setActive(undefined);setTitle("");setContext("");}}>Bản nháp mới</Button>{drafts.map(item=><Card key={item.id} className="draft-list-item"><button onClick={()=>open(item)}><strong>{String(item.payload.title??"Bản nháp chưa đặt tên")}</strong><small>{item.contribution_type} · {new Date(item.updated_at).toLocaleString("vi-VN")}</small></button><Button variant="ghost" aria-label="Xóa bản nháp" onClick={()=>remove(item)}><Trash2 size={16}/></Button></Card>)}</aside><div className="draft-editor"><label className="ps-field"><span className="ps-field-label">Loại đóng góp</span><select className="ps-select" value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(value=><option key={value}>{value}</option>)}</select></label><label className="ps-field"><span className="ps-field-label">Tiêu đề</span><input className="ps-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Bạn muốn chia sẻ điều gì?"/></label><label className="ps-field"><span className="ps-field-label">Nội dung và bối cảnh</span><textarea className="ps-textarea" rows={12} value={context} onChange={e=>setContext(e.target.value)} placeholder="Nguồn, địa điểm, ngôn ngữ, người ghi nhận và bối cảnh…"/></label><p className="draft-save-state" aria-live="polite">{saving?<><Loader2 className="ps-spin" size={15}/> Đang lưu…</>:savedAt?`Đã lưu lúc ${savedAt}`:"Nhập nội dung để bắt đầu autosave"}</p>{error&&<FeedbackState title="Có sự cố" description={error}/>}<Link href="/contribute" className="ps-btn ps-btn--primary"><FilePenLine size={16}/> Tiếp tục gửi đóng góp</Link></div></section></main>}
