import { BadRequestException,Inject,Injectable } from "@nestjs/common";
import type { Pool } from "pg";
import { PG_POOL } from "../../../common/database/database.module";
const EVENTS=new Set(["AUTH_SUCCESS","PAGE_VIEW","SEARCH","SCAN","MAP_VIEW","PLACE_VIEW","SAVE","QUIZ","CONTRIBUTION","PUBLISH"]);
@Injectable() export class AnalyticsService{constructor(@Inject(PG_POOL)private readonly pool:Pool){}
 async track(userId:string,input:{eventName:string;properties?:Record<string,unknown>;schemaVersion?:number}){if(!EVENTS.has(input.eventName))throw new BadRequestException("Su kien analytics khong hop le.");const opt=await this.pool.query(`SELECT analytics_opt_out FROM iam.users WHERE id=$1`,[userId]);if(opt.rows[0]?.analytics_opt_out)return {accepted:false,optedOut:true};const properties=input.properties??{};for(const key of Object.keys(properties)){if(["email","name","phone","token","query","text"].some(word=>key.toLowerCase().includes(word)))delete properties[key];}await this.pool.query(`INSERT INTO ops.analytics_events(user_id,event_name,schema_version,properties) VALUES($1,$2,$3,$4)`,[userId,input.eventName,input.schemaVersion??1,JSON.stringify(properties)]);return {accepted:true};}
 async setOptOut(userId:string,optOut:boolean){await this.pool.query(`UPDATE iam.users SET analytics_opt_out=$2,updated_at=now() WHERE id=$1`,[userId,optOut]);return {optOut};}
 async overview(){const {rows}=await this.pool.query(`SELECT (SELECT COUNT(*) FROM heritage.entities) AS content_count,(SELECT COUNT(*) FROM contribution.contributions WHERE status IN ('SUBMITTED','TRIAGE','EXPERT_REVIEW','RIGHTS_REVIEW')) AS review_backlog,(SELECT COUNT(*) FROM scanner.scan_requests WHERE status='COMPLETED') AS scan_success,(SELECT COUNT(*) FROM scanner.scan_requests WHERE status='FAILED') AS scan_failure,(SELECT COUNT(*) FROM ops.analytics_events WHERE occurred_at>now()-interval '30 days') AS usage_30d`);return rows[0];}
 async technical(){const {rows}=await this.pool.query(`SELECT (SELECT COUNT(*) FROM contribution.contributions WHERE status IN ('SUBMITTED','TRIAGE')) AS queue_depth,(SELECT COUNT(*) FROM ops.delivery_attempts WHERE status='FAILED') AS delivery_failures,(SELECT COUNT(*) FROM ops.analytics_events WHERE occurred_at>now()-interval '1 hour') AS events_last_hour`);return {...rows[0],generatedAt:new Date().toISOString()};}
}
