"use client";
import { useEffect, useState } from "react";
import { Building2, Check, ClipboardCheck, Loader2, RefreshCw, ShieldCheck, X } from "lucide-react";
import { ApiError, approveOrganization, listPendingOrganizations, rejectOrganization, type Organization } from "../../../lib/api-client";
import { Button, CardSkeleton, FeedbackState, PageHeader } from "../../../components/ui";
const LABELS: Record<string, string> = { PAGODA: "Chùa", SCHOOL: "Trường học", CLUB: "Câu lạc bộ", MUSEUM: "Bảo tàng", AGENCY: "Cơ quan", PROJECT_TEAM: "Đội dự án" };
export default function AdminOrganizationsPage() {
 const [items, setItems] = useState<Organization[]>([]); const [reasons, setReasons] = useState<Record<string,string>>({}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string>(); const [error,setError]=useState<string>();
 function load(){setLoading(true);setError(undefined);listPendingOrganizations().then(setItems).catch((err)=>setError(err instanceof ApiError?err.message:"Không tải được hàng đợi.")).finally(()=>setLoading(false));} useEffect(load,[]);
 async function approve(id:string){setBusy(id);setError(undefined);try{await approveOrganization(id);load();}catch(err){setError(err instanceof ApiError?err.message:"Không duyệt được tổ chức.");}finally{setBusy(undefined);}}
 async function reject(id:string){const reason=reasons[id]?.trim();if(!reason)return setError("Cần ghi lý do trước khi từ chối tổ chức.");setBusy(id);setError(undefined);try{await rejectOrganization(id,reason);load();}catch(err){setError(err instanceof ApiError?err.message:"Không từ chối được tổ chức.");}finally{setBusy(undefined);}}
 return <main className="app-page org-approval"><PageHeader eyebrow="System Administration" title="Xác minh tổ chức" subtitle="Mỗi quyết định phải dựa trên hồ sơ và có thể truy vết." actions={<Button variant="secondary" onClick={load}><RefreshCw size={16}/> Làm mới</Button>}/><section className="org-approval__layout"><div className="org-approval__summary"><ClipboardCheck size={21}/><div><strong>{items.length} yêu cầu đang chờ</strong><span>Duyệt sẽ kích hoạt quyền quản lý tổ chức.</span></div></div>{error&&<FeedbackState title="Có lỗi trong hàng đợi" description={error} action={<Button onClick={()=>setError(undefined)}>Đóng</Button>}/>} {loading&&<div className="org-approval__grid">{[1,2,3].map(i=><CardSkeleton key={i} lines={4}/>)}</div>}{!loading&&!error&&!items.length&&<div className="org-approval__empty"><ShieldCheck size={31}/><h2>Không có yêu cầu chờ duyệt</h2><p>Hàng đợi hiện đã được xử lý hết.</p></div>}<div className="org-approval__grid">{items.map(org=><article className="org-request" key={org.id}><div className="org-request__title"><span><Building2 size={20}/></span><div><small>{LABELS[org.orgType]??org.orgType}</small><h2>{org.name}</h2></div></div><label className="ps-field"><span className="ps-field-label">Lý do nếu từ chối</span><textarea className="ps-textarea" rows={3} value={reasons[org.id]??""} onChange={e=>setReasons(old=>({...old,[org.id]:e.target.value}))} placeholder="Giải thích rõ để người đăng ký hiểu…"/></label><div><Button disabled={busy===org.id} onClick={()=>approve(org.id)}>{busy===org.id?<Loader2 className="ps-spin" size={16}/>:<Check size={16}/>} Duyệt</Button><Button variant="danger" disabled={busy===org.id} onClick={()=>reject(org.id)}><X size={16}/> Từ chối</Button></div></article>)}</div></section></main>;
}
