"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, PartyPopper, RotateCcw, X } from "lucide-react";
import { ApiError, getSoloQuiz, submitSoloAnswer, type QuizQuestion, type QuizSubmissionResult } from "../../../lib/api-client";
import { Button, Card, CardSkeleton, FeedbackState, PageHeader } from "../../../components/ui";
const SOLO_QUIZ_COUNT = 5;
export default function SoloQuizPage() {
  const [questions, setQuestions] = useState<QuizQuestion[]>([]); const [index, setIndex] = useState(0); const [result, setResult] = useState<QuizSubmissionResult | null>(null); const [score, setScore] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [submitting, setSubmitting] = useState(false); useEffect(() => { getSoloQuiz(SOLO_QUIZ_COUNT).then(setQuestions).catch((err) => setError(err instanceof ApiError ? err.message : "Không tải được câu hỏi.")).finally(() => setLoading(false)); }, []); const current = questions[index];
  async function answer(choiceId: string) { if (!current || submitting || result) return; setSubmitting(true); try { const value = await submitSoloAnswer(current.id, choiceId); setResult(value); if (value.isCorrect) setScore((old) => old + 1); } catch (err) { setError(err instanceof ApiError ? err.message : "Không gửi được câu trả lời."); } finally { setSubmitting(false); } }
  function next() { setResult(null); setError(undefined); setIndex((old) => old + 1); }
  if (loading) return <main className="quiz-play"><PageHeader backHref="/quiz" title="Đang chuẩn bị thử thách" /><div className="quiz-shell"><CardSkeleton lines={5} /></div></main>;
  if (error && questions.length === 0) return <main className="quiz-play"><PageHeader backHref="/quiz" title="Quiz cá nhân" /><div className="quiz-shell"><FeedbackState title="Không tải được câu hỏi" description={error} action={<Link href="/quiz" className="ps-btn ps-btn--secondary">Quay lại</Link>} /></div></main>;
  if (!questions.length) return <main className="quiz-play"><PageHeader backHref="/quiz" title="Quiz cá nhân" /><div className="quiz-shell"><FeedbackState title="Chưa có câu hỏi" description="Kho câu hỏi hiện chưa sẵn sàng. Hãy quay lại sau." /></div></main>;
  if (index >= questions.length) return <main className="quiz-play"><div className="quiz-finish"><span><PartyPopper size={34} /></span><small>HOÀN THÀNH</small><h1>{score >= 4 ? "Bạn hiểu rất tốt!" : "Một lượt học đáng giá"}</h1><div className="quiz-score"><strong>{score}</strong><span>/ {questions.length} câu đúng</span></div><p>{score >= 4 ? "Kiến thức văn hóa của bạn thật ấn tượng." : "Hãy xem đây là bước đầu và thử lại để ghi nhớ tốt hơn."}</p><div><Link href="/quiz" className="ps-btn ps-btn--secondary">Về trang đố vui</Link><Button onClick={() => window.location.reload()}><RotateCcw size={16} /> Làm lượt mới</Button></div></div></main>;
  const progress = ((index + 1) / questions.length) * 100;
  return <main className="quiz-play"><PageHeader backHref="/quiz" eyebrow="Quiz cá nhân" title={`Câu ${index + 1} / ${questions.length}`} actions={<span className="quiz-live-score"><CheckCircle2 size={16} /> {score} câu đúng</span>} /><section className="quiz-shell"><div className="quiz-progress" role="progressbar" aria-label="Tiến độ quiz" aria-valuemin={0} aria-valuemax={questions.length} aria-valuenow={index + 1}><span style={{ width: `${progress}%` }} /></div><Card className="quiz-question"><small>CÂU HỎI {index + 1}</small><h1>{current.questionText}</h1><div className="quiz-choices">{current.choices.map((choice, order) => <button key={choice.id} type="button" disabled={!!result || submitting} onClick={() => answer(choice.id)} className={`quiz-choice ${choiceStateClass(result, choice.id)}`}><span>{String.fromCharCode(65 + order)}</span><strong>{choice.text}</strong>{result?.correctChoiceId === choice.id && <Check size={18} />}{result?.selectedChoiceId === choice.id && !result.isCorrect && <X size={18} />}</button>)}</div></Card>{result && <Card className={`quiz-feedback quiz-feedback--${result.isCorrect ? "correct" : "wrong"}`}><span>{result.isCorrect ? <CheckCircle2 size={22} /> : <X size={22} />}</span><div><h2>{result.isCorrect ? "Chính xác!" : "Chưa đúng — cùng xem lời giải"}</h2>{result.explanation && <p>{result.explanation}</p>}</div><Button onClick={next}>{index + 1 < questions.length ? "Câu tiếp theo" : "Xem kết quả"} <ArrowRight size={16} /></Button></Card>}{error && <FeedbackState title="Chưa gửi được đáp án" description={error} />}</section></main>;
}
function choiceStateClass(result: QuizSubmissionResult | null, choiceId: string) { if (!result) return ""; if (result.correctChoiceId === choiceId) return "quiz-choice--correct"; if (result.selectedChoiceId === choiceId) return "quiz-choice--wrong"; return "quiz-choice--muted"; }
