"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, Brain, Mic, Plus, Search } from "lucide-react";
import { ApiError, listTerms, type HandbookTerm } from "../../lib/api-client";
import { BottomNav } from "../../components/BottomNav";
import { Button, CardSkeleton, FeedbackState, PageHeader, SearchBar } from "../../components/ui";
export default function HandbookPage() {
  const [terms,setTerms]=useState<HandbookTerm[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true); const [error,setError]=useState<string>(); const [retry,setRetry]=useState(0);
  useEffect(()=>{setLoading(true);setError(undefined);const handle=setTimeout(()=>{listTerms({q:query.trim()||undefined}).then(setTerms).catch(e=>setError(e instanceof ApiError?e.message:"Không tải được sổ tay.")).finally(()=>setLoading(false));},250);return()=>clearTimeout(handle);},[query,retry]);
  return <main className="app-page handbook-page"><PageHeader eyebrow="Cẩm nang ngôn ngữ" title="Tiếng Khmer trong đời sống" subtitle="Nghe phát âm người bản địa, hiểu nghĩa và ôn tập theo tiến độ của riêng bạn." actions={<><Link href="/handbook/practice" className="ps-btn ps-btn--primary"><Brain size={17}/> Luyện flashcard</Link><Link href="/contribute" className="ps-btn ps-btn--secondary"><Plus size={17}/> Đóng góp phát âm</Link></>}/><section className="handbook-layout"><div className="handbook-intro"><BookOpen size={24}/><div><strong>Học theo ngữ cảnh văn hóa</strong><span>Tìm bằng chữ Khmer, phiên âm, nghĩa tiếng Việt hoặc tiếng Anh.</span></div></div><SearchBar value={query} onChange={e=>setQuery(e.target.value)} onClear={()=>setQuery("")} placeholder="Tìm chữ Khmer, phiên âm, nghĩa Việt/Anh" label="Tìm trong sổ tay"/><div className="handbook-meta"><span>{loading?"Đang tìm…":`${terms.length} từ vựng`}</span>{query&&<Button variant="ghost" onClick={()=>setQuery("")}>Xóa tìm kiếm</Button>}</div>{error&&<FeedbackState title="Không tải được từ vựng" description={error} action={<Button onClick={()=>setRetry(v=>v+1)}>Thử lại</Button>}/>} {loading&&<div className="handbook-grid">{Array.from({length:6},(_,i)=><CardSkeleton key={i} lines={2}/>)}</div>} {!loading&&!error&&!terms.length&&<div className="handbook-empty"><Search size={28}/><h2>Không tìm thấy từ phù hợp</h2><p>Thử cách viết, phiên âm hoặc nghĩa ngắn hơn.</p><Button variant="secondary" onClick={()=>setQuery("")}>Xem toàn bộ từ</Button></div>} {!loading&&!error&&terms.length>0&&<div className="handbook-grid">{terms.map(term=><Link className="term-card" key={term.id} href={`/handbook/${term.id}`}><span className="term-card__audio"><Mic size={18}/></span><div><strong lang="km">{term.khmerText}</strong>{term.latinTransliteration&&<small>{term.latinTransliteration}</small>}<p>{term.meaningVi}</p></div><ArrowRight size={17}/></Link>)}</div>}</section><BottomNav/></main>;
}
